package com.acltabontabon.vortex.core.evidence;

import com.acltabontabon.vortex.core.analysis.Analysis;
import com.acltabontabon.vortex.core.analysis.AnalysisProvenance;
import com.acltabontabon.vortex.core.analysis.Finding;
import com.acltabontabon.vortex.core.analysis.MissingTelemetry;
import com.acltabontabon.vortex.core.analysis.NextTestSuggestion;
import com.acltabontabon.vortex.core.analysis.Recommendation;
import java.util.List;
import java.util.Optional;

/**
 * The language model's reading of results that were already calculated without it.
 *
 * <p>Present in the evidence model so that a report can show it, and separated from every other
 * field so that a report cannot show it as a measurement. This is the fourth tier and the only one
 * that is not reproducible: re-running it with a different model gives a different answer, while
 * every other number in a {@link RunEvidence} is fixed the moment the run completes.
 *
 * <p>Renderers must present this visually distinct from the tiers above it and must name the model
 * that produced it. A reader has to be able to tell a measurement from an opinion at a glance.
 *
 * <p>It carries {@code provenance} for the same reason a {@code MetricObservation} does: which model
 * said something is part of how much the statement is worth.
 */
public record Interpretation(
        String conclusion,
        List<Finding> findings,
        List<Recommendation> recommendations,
        List<MissingTelemetry> missingTelemetry,
        NextTestSuggestion nextTest,
        AnalysisProvenance provenance) {

    public Interpretation {
        conclusion = conclusion == null ? "" : conclusion;
        findings = findings == null ? List.of() : List.copyOf(findings);
        recommendations = recommendations == null ? List.of() : List.copyOf(recommendations);
        missingTelemetry = missingTelemetry == null ? List.of() : List.copyOf(missingTelemetry);
    }

    /**
     * Adapts a completed analysis, or nothing when there is no usable interpretation.
     *
     * <p>A failed or pending analysis becomes absent rather than an empty panel: a report that shows
     * a heading with nothing under it invites the reader to wonder what was withheld.
     */
    public static Optional<Interpretation> from(Analysis analysis) {
        if (analysis == null || !analysis.isUsable()) {
            return Optional.empty();
        }
        return Optional.of(new Interpretation(
                analysis.conclusion(), analysis.findings(), analysis.recommendations(),
                analysis.missingTelemetry(), analysis.nextTest(), analysis.provenance()));
    }

    public Optional<NextTestSuggestion> nextTestIfPresent() {
        return Optional.ofNullable(nextTest);
    }

    /** How this interpretation must be introduced wherever it appears. */
    public String disclaimer() {
        return "Generated by a language model from the calculated results above. "
                + "It cannot change any of them.";
    }
}
