package dev.vortex.core.plan;

/**
 * Where the executable load-generator script came from.
 *
 * <p>The distinction carries real consequences. A script Vortex generated is fully understood by
 * Vortex: it knows which operation each k6 scenario drives, at what level, and what the summary will
 * contain. An imported script is arbitrary code that Vortex runs but does not comprehend, so
 * introspection is reduced and the trust boundary is different.
 *
 * <p>Named for the script rather than the workload, because {@code Workload} now means something
 * specific in Vortex — the workload experiment — and this says nothing about that.
 */
public enum ScriptSource {

    /**
     * Generated by Vortex from a workload's operation mix and workload. Vortex assigned every k6
     * workload key itself, so per-operation introspection is available.
     */
    GENERATED("Generated by Vortex"),

    /**
     * A k6 script supplied by the user. The script is executed unmodified — Vortex does not rewrite
     * it — so whatever summary handling the author chose is preserved, and Vortex falls back to
     * aggregate k6 output for its own metrics.
     */
    IMPORTED("Imported k6 script");

    private final String label;

    ScriptSource(String label) {
        this.label = label;
    }

    public String label() {
        return label;
    }

    /**
     * Whether Vortex can attribute measurements to individual operations for scripts from this
     * source.
     *
     * <p>False for imported scripts: attribution relies on the plan recording which k6 scenario key
     * belongs to which operation, and Vortex did not choose the keys in a script it did not write.
     */
    public boolean supportsPerOperationMetrics() {
        return this == GENERATED;
    }
}
